#!/bin/sh
coverage run manage.py test --settings=turtlecrossing.settings.test "$@" osnap
coverage run -a manage.py test --settings=turtlecrossing.settings.vanillatest "$@" democracy
coverage html --include='apps/*' -d coverage

